name: Build Geode Mod

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows 64-bit
            os: windows-latest
            target: Win64
          - name: Android 32-bit
            os: ubuntu-latest
            target: Android32
          - name: Android 64-bit
            os: ubuntu-latest
            target: Android64

    steps:
      - uses: actions/checkout@v4

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          target: ${{ matrix.config.target }}
